### ISSUE TITLE
EVENEMENT - Vérifier que la date et l'heure de début est antérieure à l'heure de fin

### ISSUE THREAD

**Issue by cchampou** [cchampou/protec-api#10]
Mettre en place une vérification avec message d'erreur, en respectant la règle métier suivante : **La date et heure de début doit être strictement antérieure à la date et heure de fin**

**Comment by cmoysan** [comment]
**Ok, par contre il faudra améliorer les messages d'erreurs par la suite.**

**Comment by cchampou** [comment]
> **Ok, par contre il faudra améliorer les messages d'erreurs par la suite.**

Tu peux me dire auquel tu fais ref pour que je puisse le corriger ?

**Comment by cmoysan** [comment]
Quand je renseigne une date/heure de fin antérieure à la date/heure de début, avoir un message du style : La date de début doit commencer avant la date de fin. Mais j'ai pas encore décidé des textes :-P

**Comment by cchampou** [comment]
Je met en done vu que l'autre ticket #13 traite des erreurs 😉
