### ISSUE TITLE
ADMIN - Faire en sorte que l'événement ne soit pas indiqué comme consulté par moi.

### ISSUE THREAD

**Issue by cchampou** [cchampou/protec-api#16]
1. Je suis connecté en tant que clement.moysan@gmail.com sur l'admin.
2. Je créé l'événément
3. Je vais sur le détail de l'événément au sein de l'admin
4. Je clic sur alerter par email/notification/sms/appel

## Résultat attendue

Sur ma ligne, Clément Moysan, au sein de la colonne, j'ai le statut `Non consulté`

## Résultat obtenu

Sur ma ligne, Clément Moysan, au sein de la colonne, j'ai le statut `consulté, en attente de réponse`

**Comment by cchampou** [comment]
Je ne sais pas comment faire ça pour l'instant, je reviendrai dessus.

**Comment by cchampou** [comment]
Finalement c'est bon. J'ai trouvé un moyen simple 🚀

**Comment by cmoysan** [comment]
Ok pour moi.
