### ISSUE TITLE
Notification - Email - Changer le titre et le contenu

### ISSUE THREAD

**Issue by cchampou** [cchampou/protec-api#17]
## Objet

[Protection Civile] URGENT - Recensement - `<titre>` (`<titre>` correspondant au titre de l'événement)

## Contenu

Bonjour,

Suite à une demande urgente, nous recensons le personnel disponible :

- Titre : `<titre>` (`<titre>` correspondant au titre de l'événement)
- Lieu RDV : `<lieu rdv>` (`<lieu rdv>` correspondant au lieu de l'événement)
- Début : `<date/heure début, format : “dd/mm/YYYY - HH:ii”>` (`<date/heure début, format : “dd/mm/YYYY - HH:ii”>` correspondant au champ date de début et au champ heure de début de l'événement)
- Fin : `<date/heure fin, format : “dd/mm/YYYY - HH:ii”>` (`<date/heure fin, format : “dd/mm/YYYY - HH:ii”>` correspondant au champ date de fin et au champ heure de fin de l'événement)
- Commentaires : `<commentaires>` (`<commentaires>` correspondant au champ Commentaire de l'événement)

Merci de faire un retour dès que possible via l’application.

`<deep link>`  (`<deep link>` lien à générer, permettant d'accéder directement à l'événement)

Attention, ceci n’est pas une convocation.

*Cet email est généré automatiquement par ProtecApp.*

Protection Civile du Rhône

**Comment by cmoysan** [comment]
Test effectué, voici mes retours :

- au niveau de l'heure de début et de fin, ne pas afficher les secondes
- Dans le champ commentaire, conserver les sauts de ligne

@cchampou

**Comment by cchampou** [comment]
Corrigé ✅

**Comment by cmoysan** [comment]
> Ok, go pour la beta
